"""mng 빈 화면 긴급 진단."""
import os, sys
sys.stdout.reconfigure(encoding="utf-8", errors="replace")
import paramiko
c = paramiko.SSHClient()
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect("104.64.128.103", 22, "root", os.environ["SSHPASS"], allow_agent=False, look_for_keys=False, timeout=15)
print("=== mng index.html 시점 ===")
_, o, _ = c.exec_command("ls -la /data/wwwroot/sajumoon.co.kr/mng/index.html", get_pty=False)
print(o.read().decode("utf-8", errors="replace"))
print()
print("=== index.html 가리키는 JS hash ===")
_, o, _ = c.exec_command("grep -oE 'index-[A-Za-z0-9_-]+\\.js' /data/wwwroot/sajumoon.co.kr/mng/index.html | head -1", get_pty=False)
js_hash = o.read().decode("utf-8", errors="replace").strip()
print(js_hash)
print()
print("=== 그 JS 파일이 prod 에 존재하는지 ===")
_, o, _ = c.exec_command(f"ls -la /data/wwwroot/sajumoon.co.kr/mng/assets/{js_hash} 2>&1", get_pty=False)
print(o.read().decode("utf-8", errors="replace"))
print()
print("=== HTTP 응답 ===")
_, o, _ = c.exec_command(f'curl -s -o /dev/null -w "%{{http_code}} %{{size_download}}" https://sajuplan.com/mng/assets/{js_hash}', get_pty=False)
print(o.read().decode("utf-8", errors="replace"))
c.close()
